runtime: nodejs20

env_variables:
  NODE_ENV: production
  DATABASE_URL: "postgresql://postgres:Password-1@10.3.112.3:5432/postgres"
  GROQ_API_KEY: "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"

# For Cloud SQL connection
vpc_access_connector:
  name: "projects/my-k8-project-435819/locations/europe-west4/connectors/my-vpc-db"
#  egress_setting: all-traffic 

# Optional: For larger file uploads
automatic_scaling:
  max_instances: 10
  min_instances: 1

# Handle Node.js build
build_env_variables:
  NODE_ENV: development
