runtime: nodejs20
env: standard

entrypoint: npm start

env_variables:
  NODE_ENV: "production"
  # Uncomment and set your actual values:
  # DATABASE_URL: "postgresql://user:password@host:port/database"
  # GROQ_API_KEY: "your-groq-api-key-here"