runtime: nodejs20

env_variables:
  NODE_ENV: production
  # Use the replit DATABASE_URL which works in both development and App Engine
  DATABASE_URL: ${DATABASE_URL}
  GROQ_API_KEY: ${GROQ_API_KEY}

# Optional: For larger file uploads
automatic_scaling:
  max_instances: 10
  min_instances: 1

# Handle Node.js build with dev dependencies
build_env_variables:
  NODE_ENV: development

# Custom build commands to ensure dev dependencies are installed
entrypoint: npm start